### ISSUE TITLE
Cannot invoke "org.metaborg.core.MetaBorg.close()" because "this.metaborg" is null

### ISSUE THREAD

**Issue by johannes-riecken** [metaborg/spoofax#91]
I'm trying to install spoofax-releng from source on Ubuntu 23.04 (where my goal is to find a way to run sdf2table on my Mac M1 for which I want to try using an x86_64 Docker container), but there are failing tests. 
I cloned and updated submodules on Oct 20, which is commit 7e9b2d3 of spoofax-releng.
Here's an excerpt from where the first `[ERROR]` lines appear:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.metaborg.spoofax.core.test.language.SpoofaxLanguageIdentificationTest
[INFO] Running org.metaborg.spoofax.core.test.language.SpoofaxLanguageTest
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.825 s <<< FAILURE! - in org.metaborg.spoofax.core.test.language.SpoofaxLanguageIdentificationTest
[ERROR] conflictingExtension  Time elapsed: 2.559 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
	java.lang.NullPointerException: Cannot invoke "org.metaborg.core.MetaBorg.close()" because "this.metaborg" is null

[ERROR] identification  Time elapsed: 0.213 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
	java.lang.NullPointerException: Cannot invoke "org.metaborg.core.MetaBorg.close()" because "this.metaborg" is null

[ERROR] Tests run: 13, Failures: 13, Errors: 0, Skipped: 0, Time elapsed: 4.833 s <<< FAILURE! - in org.metaborg.spoofax.core.test.language.SpoofaxLanguageTest
[ERROR] discoverLanguage  Time elapsed: 2.725 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
```

**Comment by Apanatshka** [comment]
If you're trying to work around the issue of running the 32-bit sdf2table binary on a Mac, I can recommend switching your Spoofax project settings to use `sdftable: java` (in the metaborg.yaml file), which runs a newer Java implementation.

If you want to continue your current approach, with building Spoofax from source, I would advise you to go through the steps described here first: https://spoofax.dev/howtos/development/
If the errors persist, please report back and I'll see if I can start to reproduce your setup.

@Virtlink is familiar with your goal of running sdf2table in a docker container, and may be able to explain where are current code is to do that. We already ran into that issue when Mac OS on Intel stopped supporting 32-bit executables...

**Comment by johannes-riecken** [comment]
Thanks, that worked! I also noticed that `sdf2table` still compiles fine in the Docker container in spite of the other errors.
