### ISSUE TITLE
Can not create a new project

### ISSUE THREAD

**Issue by alan-insam** [metaborg/spoofax#92]
Eclipse: org.eclipse.platform.ide 4.16.0.I20200604-0540
Spoofax: org.metaborg.spoofax.eclipse 2.5.19
System: Windows 10 amd64 10.0

I installed Spoofax on [https://spoofax.dev/howtos/installation/install-eclipse-bundle/](the official site) for windows x64 64 bit (the latest stable version). I unpacked the ZIP, run eclipse.exe and then:

File -> New -> Project ... -> Spoofax -> Spoofax -> Spoofax language project

I can not click on "next" or "finish"

![image](https://github.com/metaborg/spoofax/assets/53089720/ef43140c-aa5e-4d11-9fee-67aadc2bb52b)

The same error ocurs when I install the latest Eclipse version + Spoofax by Plugin.

**Comment by Apanatshka** [comment]
Thanks for the detailed report. I can reproduce this problem on a different OS and CPU architecture, so it's definitely just on us. I've documented this as a known issue in the release notes of the version for now.

As a workaround, try one version earlier: https://spoofax.dev/release/note/2.5.18/

I'll see if someone from our team can find time in the coming weeks to investigate the problem.

**Comment by alan-insam** [comment]
2.5.18 does not work either (failed to load language artifacts) 2.5.17
works and I currently use it.


Thank you!

Jeff Smits ***@***.***> schrieb am Fr., 26. Jan. 2024, 14:43:

**Comment by AZWN** [comment]
Fixed in 9973cbcc6be8a7dbc99c122570b5685a9593212f

**Comment by Apanatshka** [comment]
The fix has now been released in Spoofax 2.5.20.
